services:
  - type: web
    name: job-scheduler
    runtime: docker
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/jobscheduler-0.0.1-SNAPSHOT.jar"
    envVars: []
